In [2]:
# Write a Python program to print the NumPy
# version in your system.
import numpy as np
print(np.__version__)

1.18.5


In [12]:
# Write a Python program to reverse an array
# (first element becomes last).

#Method1
# arr1 = np.arange(6)
# arr1[::-1]

#Method2
# arr1 = np.arange(6)
# res = list(reversed(arr1))
# res


[5, 4, 3, 2, 1, 0]

In [14]:
# Write a Python program to convert a list and
# tuple into arrays.

lst = [1,2,3,6,8]
tpl = (9,8,7,6,5)

arr1 = np.array(lst)
arr2 = np.array(tpl)
print(arr1)
print(arr2)

[1 2 3 6 8]
[9 8 7 6 5]


In [16]:
# Write a Python program to find common values
# between two arrays.

np.intersect1d(arr1,arr2)


array([6, 8])

In [19]:
# Write a Python program compare two arrays
# using numpy.

print(np.less_equal(arr1,arr2))
print(np.greater_equal(arr1,arr2))
print(np.equal(arr1,arr2))

[ True  True  True  True False]
[False False False  True  True]
[False False False  True False]


In [22]:
# Write a Python program to change the
# dimension of an array

np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
# Write a Python program (using numpy) to sum
# of all the multiples of 3 or 5 below 100

arr3 = np.arange(100)
arr4 = arr3[(arr3%3==0) | (arr3%5==0)]
arr4.sum()

2318

In [26]:
# Write a Python program to convert a NumPy
# array into Python list structure

lst = list(arr4)
print(lst)

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]


In [33]:
# Write a Python program to how to add an extra
# column to a numpy array

array1 = np.arange(6).reshape(3,2)
array2 = np.arange(3).reshape(3,1)
np.append(array1,array2, axis=1)

array([[0, 1, 0],
       [2, 3, 1],
       [4, 5, 2]])

In [40]:
# Write a Python program to check whether the
# numpy array is empty or not

arr1 = np.arange(0)
arr1.size

0

In [49]:
# Write a Python program to normalize a 3x3
# random matrix.

arr1 = np.random.randint(1,10,(3,3),dtype=int)
print(arr1)
max1 = arr1.max()
print(max1)
min1 = arr1.min()
print(min1)
arr1 = (arr1-min1)/(max1-min1)
print(arr1)

[[9 3 4]
 [9 8 4]
 [3 5 9]]
9
3
[[1.         0.         0.16666667]
 [1.         0.83333333 0.16666667]
 [0.         0.33333333 1.        ]]


In [51]:
# How to ignore all numpy warnings (not
# recommended)?

defaults = np.seterr(all = 'Ignore')
z = np.ones(1)/0

KeyError: 'Ignore'

In [53]:
# How to swap two rows of an array?
my_array = np.arange(12).reshape(3, 4)
print(my_array)
print()
my_array[[0,1],:] = my_array[[1,0],:]
print(my_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e.,
# resample the elements of an array with replacement N times, compute the mean of
# each sample, and then compute percentiles over the means)

In [72]:
# Python program to create a random vector of
# size 10 and sort it.
arr1 = np.random.randint(1,100,5,dtype = int)
arr1.sort()
arr1

array([ 6, 28, 49, 73, 89])

In [68]:
# Write a Python program to check two random
# arrays are equal or not.

arr1 = np.random.randint(1,10,(2,2),dtype = int)
arr2 = np.random.randint(1,10,(2,2),dtype = int)
print(arr1==arr2)

[[False False]
 [False False]]


In [67]:
# Write a Python program to add, subtract,
# multiply, divide arguments element-wise.

arr1 = np.arange(5)
arr2 = np.arange(6,11)
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[0 1 2 3 4]
[ 6  7  8  9 10]
[ 6  8 10 12 14]
[-6 -6 -6 -6 -6]
[ 0  7 16 27 40]
[0.         0.14285714 0.25       0.33333333 0.4       ]


In [60]:
# Write a Python program to get the dates of
# yesterday, today and tomorrow.

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)
today = np.datetime64('today', 'D') 
print("Today: ", today)

Yesterday:  2020-12-02
Tomorrow:  2020-12-04
Today:  2020-12-03
